#!/usr/bin/env python3
"""
Pixiv 图片爬虫 — 按点赞数爬取指定 Tag 下的热门图片
用法: python pixiv_scraper.py
首次运行需手动登录，之后自动复用 Cookie。
"""

import os, re, io, json, time, random, pickle, tempfile, urllib.parse, sys, subprocess, threading, traceback, sqlite3, zipfile
from concurrent.futures import ThreadPoolExecutor
from pathlib import Path

import requests
try:
    from PIL import Image      # 仅动图合成为 GIF 需要；缺失时不影响其它功能
except Exception:
    Image = None
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.chrome.options import Options as ChromeOpts
from selenium.webdriver.chrome.service import Service as ChromeSvc
from selenium.webdriver.edge.options import Options as EdgeOpts
from selenium.webdriver.edge.service import Service as EdgeSvc
from selenium.common.exceptions import NoSuchElementException

# 检测是否打包为 exe（PyInstaller）
_is_frozen = getattr(sys, "frozen", False)
_base_dir = os.path.dirname(sys.executable) if _is_frozen else os.path.dirname(os.path.abspath(__file__))

# ============================================================
CONFIG = {
    "tag": "天童ケイ",          # 搜索标签（日文结果更多）
    "order": "popular_d",              # popular_d / date_d / popular_male_d / popular_female_d
    "max_images": 60,                  # 下载数量
    "download_dir": os.path.join(_base_dir, "downloads"),
    "cookie_file": os.path.join(_base_dir, "cookies.pkl"),
    "show_browser": True,              # 首次登录建议 True
    "api_delay": 0.8,                  # API 请求间隔（秒）
    "download_delay": 0.8,             # 图片下载间隔（秒）时
    "browser": "auto",                 # auto / chrome / edge
    "browser_path": None,              # 留空自动查找
    "webdriver_path": None,            # 留空自动查找
    "filter_ai": True,                 # 过滤 AI 生成
    "min_likes": 50,                  # 最低点赞数（0=不过滤）
    "ai_tags": [
        "AI", "AI生成", "AIイラスト", "AIart", "AIアート", "AIillust",
        "NovelAI", "StableDiffusion", "SDXL", "Midjourney", "DALL-E",
        "AI-generated", "generated by AI", "AI生成作品",
    ],
    "separate_r18": True,              # R18 分文件夹
    "include_r18": True,               # False = 只下全年龄
    "r18_only": False,                 # True = 仅下载 R18 作品
                                       #   注意: R18 需要处于登录状态, 且账号已开启
                                       #   「设置 → 閲覧設定 → R-18作品の表示」
    "organize_by_tags": True,          # 按标签分文件夹（优先使用非 AI 标签）
                                       #   也可指定标签列表: ["tagA", "tagB"]
    # ---- 查重（跨运行去重）----
    "dedup": True,                     # True = 跳过曾经遍历/下载过的作品
    "dedup_skip_filtered": True,       # True = 被过滤(低赞/AI等)的作品也跳过
                                       #   False = 每次重新检查(点赞可能涨)
    "history_db": os.path.join(_base_dir, "pixiv_history.db"),  # 记录表位置
    "tag_cache_file": os.path.join(_base_dir, "tag_suggest_cache.json"),  # 标签联想缓存
}

UA = ("Mozilla/5.0 (Windows NT 10.0; Win64; x64) "
      "AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36")

# ============================================================
# 小工具
# ============================================================

def sanitize(name: str) -> str:
    return re.sub(r'[\\/:*?"<>|]', "_", name)[:120]


def has_ai_tag(tags):
    """标签中是否含 AI 关键词（大小写不敏感）"""
    if not tags or not CONFIG.get("ai_tags"):
        return False
    ai_set = {t.lower() for t in CONFIG["ai_tags"]}
    return any(t.lower() in ai_set or
               any(ai in t.lower() for ai in ai_set)
               for t in tags)


def classify_by_tag(tags, is_r18):
    """根据标签确定目标文件夹名。
    返回 (tag_folder_name, r18_subfolder) 的元组。
    - tag_folder_name: 匹配到的标签文件夹名，None 表示不分类
    - r18_subfolder: R18 子文件夹名，空字符串表示不分 R18 子目录
    """
    org = CONFIG.get("organize_by_tags")

    # 辅助：按 separate_r18 配置决定 R18 子目录
    def _r18_sub():
        if not CONFIG.get("separate_r18"):
            return ""
        return "r18" if is_r18 else "safe"

    if not org or not tags:
        return None, _r18_sub()

    ai_set = {t.lower() for t in CONFIG.get("ai_tags", [])}

    if isinstance(org, list) and org:
        # 指定标签列表：按顺序匹配
        target_set = {t.lower() for t in org}
        for t in tags:
            if t.lower() in target_set:
                return sanitize(t), _r18_sub()
        # 不匹配任何指定标签 → 归入 "其他"
        return "其他", _r18_sub()
    elif isinstance(org, list):
        # 空列表 = 不分类
        return None, _r18_sub()

    # organize_by_tags == True: 使用第一个非 AI 标签
    for t in tags:
        tl = t.lower()
        if tl not in ai_set and not any(ai in tl for ai in ai_set):
            return sanitize(t), _r18_sub()
    # 全部是 AI 标签 → 归入 "AI"
    return "AI", _r18_sub()


# ============================================================
# 浏览器 & 登录（Selenium 仅用于登录）
# ============================================================

def _find_browser():
    """返回 (type, exe_path)"""
    bt = CONFIG["browser"]
    bp = CONFIG.get("browser_path")
    if bt != "auto" and bp:
        return bt, bp

    edge = [r"C:\Program Files (x86)\Microsoft\Edge\Application\msedge.exe",
            r"C:\Program Files\Microsoft\Edge\Application\msedge.exe"]
    chrome = [r"C:\Program Files\Google\Chrome\Application\chrome.exe",
              r"C:\Program Files (x86)\Google\Chrome\Application\chrome.exe",
              os.path.expanduser(r"~\AppData\Local\Google\Chrome\Application\chrome.exe")]

    for p in edge:
        if os.path.isfile(p) and bt in ("auto", "edge"):
            return "edge", p
    for p in chrome:
        if os.path.isfile(p) and bt in ("auto", "chrome"):
            return "chrome", p
    raise RuntimeError("未检测到 Chrome 或 Edge，请安装浏览器或在 CONFIG 中指定 browser_path。")


def _get_file_version(exe_path):
    """读取 exe 文件的 ProductVersion（如 '152.0.4191.53'），失败返回 None"""
    try:
        import ctypes
        from ctypes import wintypes
        size = ctypes.windll.version.GetFileVersionInfoSizeW(exe_path, None)
        if not size:
            return None
        buf = ctypes.create_string_buffer(size)
        if not ctypes.windll.version.GetFileVersionInfoW(exe_path, 0, size, buf):
            return None
        p = ctypes.c_void_p()
        ln = wintypes.UINT()
        if not ctypes.windll.version.VerQueryValueW(buf, r"\VarFileInfo\Translation",
                                                    ctypes.byref(p), ctypes.byref(ln)):
            return None
        import struct
        lang, codepage = struct.unpack("HH", ctypes.string_at(p, 4))
        sub = rf"\StringFileInfo\{lang:04X}{codepage:04X}\ProductVersion"
        if not ctypes.windll.version.VerQueryValueW(buf, sub,
                                                    ctypes.byref(p), ctypes.byref(ln)):
            return None
        return ctypes.wstring_at(p, ln.value - 1)
    except Exception:
        return None


def _ver_tuple(v):
    """'152.0.4191.53' -> (152, 0, 4191, 53)，解析失败返回空元组"""
    try:
        return tuple(int(x) for x in str(v).split("."))
    except Exception:
        return ()


def _find_driver(browser_type, browser_path=None):
    """查找 WebDriver 路径。
    优先级: CONFIG 指定路径 > PATH 中的驱动 > Selenium 缓存中与浏览器
    主版本匹配的驱动 > 返回 None（交由 Selenium Manager 自动下载）。
    """
    specified = CONFIG.get("webdriver_path")
    if specified and os.path.isfile(specified):
        return specified
    name = {"edge": "msedgedriver.exe", "chrome": "chromedriver.exe"}.get(browser_type, "")
    if not name:
        return None

    # 1) PATH 中查找（用户自行管理的驱动优先，但最终仍会做版本校验）
    r = subprocess.run(["where", name], capture_output=True, text=True, shell=True)
    if r.returncode == 0 and r.stdout.strip():
        return r.stdout.strip().split("\n")[0]

    # 2) Selenium Manager 缓存目录中查找与浏览器主版本匹配的驱动
    cache_dir = os.path.join(os.path.expanduser("~"), ".cache", "selenium",
                             "msedgedriver" if browser_type == "edge" else "chromedriver",
                             "win64")
    if os.path.isdir(cache_dir):
        bp = browser_path or _find_browser()[1]
        bver = _get_file_version(bp) or ""
        bmajor = _ver_tuple(bver)[:1]  # 浏览器主版本，如 (152,)
        cands = []
        for ver in os.listdir(cache_dir):
            dp = os.path.join(cache_dir, ver, name)
            if os.path.isfile(dp):
                cands.append((_ver_tuple(ver), ver, dp))
        if not cands:
            return None
        # 优先选择主版本匹配中数值最大的
        matched = [c for c in cands if bmajor and c[0][:1] == bmajor]
        chosen = sorted(matched if matched else cands,
                        key=lambda c: c[0], reverse=True)[0]
        if matched:
            _log(f"[*] 使用缓存驱动: {chosen[2]} (浏览器主版本 {bmajor[0]})")
            return chosen[2]
        _log(f"[!] 缓存驱动主版本 {chosen[0][0]} 与浏览器主版本 "
             f"{bmajor[0] if bmajor else '未知'} 不匹配，忽略缓存")
    return None


def create_driver():
    bt, bp = _find_browser()
    is_edge = bt == "edge"
    opts = EdgeOpts() if is_edge else ChromeOpts()
    svc_cls = EdgeSvc if is_edge else ChromeSvc

    if not CONFIG["show_browser"]:
        opts.add_argument("--headless=new")
        opts.add_argument("--window-size=1920,1080")
    opts.add_argument("--disable-blink-features=AutomationControlled")
    opts.add_experimental_option("excludeSwitches", ["enable-automation"])
    opts.add_experimental_option("useAutomationExtension", False)
    opts.add_argument("--no-sandbox")
    opts.add_argument("--disable-gpu")
    opts.add_argument(f"--user-agent={UA}")
    opts.add_argument("--lang=ja-JP")
    opts.binary_location = bp

    dp = _find_driver(bt, bp)
    _log(f"[*] 浏览器: {bt}  ({bp})")
    if dp:
        _log(f"[*] 使用 WebDriver: {dp}")
    else:
        _log("[*] 未找到匹配的 WebDriver，将尝试自动下载（需要网络）...")
    try:
        driver = webdriver.Edge(service=svc_cls(dp) if dp else svc_cls(), options=opts) \
            if is_edge else \
            webdriver.Chrome(service=svc_cls(dp) if dp else svc_cls(), options=opts)
    except Exception as e:
        if "version" in str(e).lower() and "only supports" in str(e).lower():
            raise RuntimeError(
                f"WebDriver 与浏览器版本不匹配，无法启动浏览器。\n"
                f"详情: {e}\n"
                f"解决: 删除 ~/.cache/selenium/{'msedgedriver' if is_edge else 'chromedriver'}"
                f" 目录后重试（将自动下载匹配版本），或手动下载匹配的 WebDriver"
                f" 并在 CONFIG['webdriver_path'] 中指定。")
        raise

    # 仅隐藏最基本的 webdriver 标记（手动登录无需过多伪装）
    driver.execute_cdp_cmd("Page.addScriptToEvaluateOnNewDocument", {"source": """
        Object.defineProperty(navigator, 'webdriver', {get: () => undefined});
    """})
    return driver


def save_cookies(driver):
    with open(CONFIG["cookie_file"], "wb") as f:
        pickle.dump(driver.get_cookies(), f)
    _log(f"[*] Cookie 已保存")


def load_cookies(driver):
    cf = CONFIG["cookie_file"]
    if not os.path.exists(cf):
        return False
    driver.get("https://www.pixiv.net/")
    time.sleep(1.5)
    with open(cf, "rb") as f:
        cookies = pickle.load(f)
    ok = 0
    for c in cookies:
        for k in ("sameSite", "httpOnly", "storeId", "hostOnly", "session"):
            c.pop(k, None)
        if "expiry" in c:
            try:
                c["expiry"] = int(float(c["expiry"]))
            except (ValueError, OverflowError):
                c.pop("expiry", None)
        try:
            driver.add_cookie(c)
            ok += 1
        except Exception:
            pass
    _log(f"[*] Cookie 加载: {ok}/{len(cookies)}")
    return ok > 0


def _make_session(cookie_dicts):
    """由 selenium 格式的 cookie 列表构造 requests 会话（校验/爬取共用）"""
    s = requests.Session()
    s.headers.update({"User-Agent": UA, "Referer": "https://www.pixiv.net/",
                      "Accept-Language": "ja-JP,ja;q=0.9,en;q=0.8"})
    for c in cookie_dicts:
        n, v = c.get("name", ""), c.get("value", "")
        if not n:
            continue
        s.cookies.set(n, v, domain=c.get("domain", ".pixiv.net"),
                      path=c.get("path", "/"))
        if n == "PHPSESSID":
            s.cookies.set(n, v, domain=".pximg.net", path="/")  # 图片 CDN
    return s


def _homepage_logged_in(session):
    """兜底校验: 解析首页服务端渲染的登录标记，返回 True/False/None"""
    try:
        h = session.get("https://www.pixiv.net/", timeout=15).text
    except Exception:
        return None
    if r'\"self\":null' in h or '"isLoggedIn":false' in h:
        return False
    if r'\"self\":{' in h or '"isLoggedIn":true' in h:
        return True
    return None


def _session_logged_in(session):
    """真实登录校验。返回 True/False，无法判断时返回 None。
    注意: pixiv 对游客也会发放 PHPSESSID，不能只看 cookie 名字！
    这里调用需要登录的接口: 游客会得到 401，登录用户返回 200。"""
    try:
        r = session.get("https://www.pixiv.net/ajax/follow_latest/illust"
                        "?p=1&mode=all&lang=ja", timeout=10)
    except Exception:
        return None
    if r.status_code == 200:
        try:
            return not r.json().get("error", False)
        except Exception:
            return _homepage_logged_in(session)
    if r.status_code == 401:
        return False
    return _homepage_logged_in(session)


def manual_login(driver):
    _log("\n" + "=" * 60)
    _log("  请在浏览器中手动登录 Pixiv")
    _log("=" * 60)
    driver.get("https://www.pixiv.net/")
    driver.maximize_window()

    def _poll_login(timeout_s=300, interval_s=2.5):
        # 轮询真实登录状态：游客也有 PHPSESSID，不能只看 cookie 是否存在
        for _ in range(max(1, int(timeout_s / interval_s))):
            if _should_stop():
                return False
            time.sleep(interval_s)
            if _session_logged_in(_make_session(driver.get_cookies())) is True:
                return True
        return False

    # 检测是否在 PyInstaller windowed 模式（无控制台 stdin）
    if _is_frozen:
        _log("[*] 等待手动登录（最多 5 分钟）...")
        _log("    请在浏览器窗口中完成登录，程序会自动检测")
        if _poll_login():
            _log("[✓] 检测到登录状态")
            time.sleep(1)
            save_cookies(driver)
        else:
            _log("[!] 登录未完成或已取消，请重新运行")
        return

    # 控制台模式：等待回车
    try:
        input("\n>>> 登录完成后按 Enter: ")
    except (EOFError, OSError):
        # stdin 不可用（被重定向等情况），回退到轮询
        _log("[*] 等待手动登录（最多 5 分钟）...")
        if _poll_login():
            _log("[✓] 检测到登录状态")
            time.sleep(1)
            save_cookies(driver)
        else:
            _log("[!] 登录未完成或已取消，请重新运行")
        return

    time.sleep(3)
    if _session_logged_in(_make_session(driver.get_cookies())) is True:
        save_cookies(driver)
        _log("[✓] 登录成功")
        return
    _log("[!] 仍未检测到登录状态（游客看不到 R18 作品），重试...")
    manual_login(driver)


def ensure_logged_in(driver):
    if load_cookies(driver):
        driver.refresh()
        time.sleep(2)
        state = _session_logged_in(_make_session(driver.get_cookies()))
        if state is True:
            _log("[✓] Cookie 有效（已登录）")
            return
        if state is None:
            _log("[!] 无法验证登录状态（网络问题？），将按未登录处理")
        else:
            _log("[!] Cookie 已失效（服务器判定为未登录），删除旧 Cookie 并重新登录")
        try:
            os.remove(CONFIG["cookie_file"])
        except OSError:
            pass
    manual_login(driver)


# ============================================================
# API 层（requests）
# ============================================================

def build_session(driver):
    # 由浏览器 cookie 构造 requests 会话（统一走 _make_session）
    return _make_session(driver.get_cookies())


def _api_get(session, url, label="API"):
    """统一 GET + 429 重试"""
    for attempt in range(2):
        resp = session.get(url, timeout=15)
        if resp.status_code == 429:
            _log(f"  [!] {label} 429，等待 30s...")
            time.sleep(30)
            continue
        return resp
    return resp


def search_api(session, tag, order, page=1, mode="all"):
    """搜索。使用 artworks 端点（与网页版一致）：只有这样才能搜到动图（illustType=2）；
    旧的 illustrations + type=illust 会把动图全部过滤掉。漫画(illustType=1)由调用方跳过。
    """
    enc = urllib.parse.quote(tag)
    url = (f"https://www.pixiv.net/ajax/search/artworks/{enc}"
           f"?word={enc}&order={order}&mode={mode}&p={page}"
           f"&s_mode=s_tag&lang=ja")
    resp = _api_get(session, url, "搜索")
    if resp.status_code != 200:
        return []
    try:
        data = resp.json()
    except Exception:
        return []
    if data.get("error"):
        return []
    body = data.get("body", {})
    items = body.get("illustManga", {}).get("data") or \
            body.get("data", [])
    if not isinstance(items, list):
        return []
    return [{"illust_id": str(i.get("id", "")),
             "title": i.get("title", ""),
             "user_id": str(i.get("userId", "")),
             "user_name": i.get("userName", ""),
             "page_count": i.get("pageCount", 1),
             "x_restrict": i.get("xRestrict") or 0,
             "illust_type": i.get("illustType") or 0}
            for i in items]


def detail_api(session, illust_id):
    d = {"illust_id": illust_id, "title": "", "author": "", "author_id": "",
         "image_urls": [], "like_count": 0, "view_count": 0,
         "bookmark_count": 0, "tags": [], "page_count": 1,
         "illust_type": 0,
         "is_r18": False, "url": f"https://www.pixiv.net/artworks/{illust_id}"}

    resp = _api_get(session,
                    f"https://www.pixiv.net/ajax/illust/{illust_id}?lang=ja",
                    "详情")
    if resp.status_code != 200:
        return d
    try:
        data = resp.json()
    except Exception:
        return d
    if data.get("error") or not isinstance(data.get("body"), dict):
        return d

    b = data["body"]
    d["title"] = b.get("title") or b.get("illustTitle", "")
    d["author"] = b.get("userName") or b.get("userAccount", "")
    d["author_id"] = str(b.get("userId", ""))
    d["like_count"] = b.get("likeCount") or b.get("bookmarkCount", 0)
    d["view_count"] = b.get("viewCount", 0)
    d["bookmark_count"] = b.get("bookmarkCount", 0)
    d["page_count"] = b.get("pageCount", 1)
    d["illust_type"] = b.get("illustType") or 0   # 2 = 动图（ugoira）
    d["is_r18"] = b.get("xRestrict", 0) > 0

    # 标签
    raw_tags = b.get("tags", {})
    if isinstance(raw_tags, dict):
        d["tags"] = [t.get("tag", "") for t in raw_tags.get("tags", []) if isinstance(t, dict)]
    elif isinstance(raw_tags, list):
        d["tags"] = [t.get("tag", t) if isinstance(t, dict) else str(t) for t in raw_tags]

    # 图片 URL
    urls = b.get("urls", {})
    for k in ("original", "regular"):
        if urls.get(k):
            d["image_urls"].append(urls[k])
            break

    # 多页
    if d["page_count"] > 1:
        pages_url = f"https://www.pixiv.net/ajax/illust/{illust_id}/pages?lang=ja"
        try:
            pr = _api_get(session, pages_url, "多页")
            if pr.status_code == 200:
                pd = pr.json().get("body", [])
                if isinstance(pd, list):
                    for pg in pd:
                        u = pg.get("urls", {})
                        for k in ("original", "regular"):
                            if u.get(k):
                                d["image_urls"].append(u[k])
                                break
        except Exception:
            pass

    return d


def ugoira_meta_api(session, illust_id):
    """动图元信息：帧序列 zip 地址 + 逐帧延迟。
    zip 优先取 pixiv 播放版（600px，体积小、与网页播放一致）。
    返回 {"zip_url": str, "frames": [{"file", "delay"}...]}，失败返回 None。
    """
    resp = _api_get(session,
                    f"https://www.pixiv.net/ajax/illust/{illust_id}/ugoira_meta?lang=ja",
                    "动图")
    if resp.status_code != 200:
        return None
    try:
        data = resp.json()
    except Exception:
        return None
    if data.get("error") or not isinstance(data.get("body"), dict):
        return None
    b = data["body"]
    zip_url = (b.get("src") or "").strip() or (b.get("originalSrc") or "").strip()
    if not zip_url:
        return None
    frames = []
    for f in (b.get("frames") or []):
        if isinstance(f, dict) and f.get("file"):
            try:
                delay = int(f.get("delay") or 100)
            except (TypeError, ValueError):
                delay = 100
            frames.append({"file": str(f["file"]), "delay": max(10, delay)})
    return {"zip_url": zip_url, "frames": frames}


def download_ugoira(d, folder, api_session):
    """下载动图（ugoira）并合成为可播放的 GIF。

    pixiv 的"原图"只是静态首帧（urls.original），真正的动画在 ugoira_meta 的
    帧序列 zip 里；这里下载 zip 后用 Pillow 合成：逐帧延迟按 pixiv 元数据、
    无限循环、长边封顶 600（与网页播放版一致）。成功返回 GIF 路径，失败返回 None。
    """
    lid = str(d["illust_id"])
    if Image is None:
        _log("  [动图] 未安装 Pillow，无法合成 GIF（pip install pillow）")
        return None

    meta = ugoira_meta_api(api_session, lid)
    if not meta:
        _log("  [动图] 元信息获取失败")
        return None
    frames_meta = meta["frames"]
    _log(f"  [动图] 下载动图包（{len(frames_meta)} 帧）...")

    tmp_path = None
    try:
        fd, tmp_path = tempfile.mkstemp(suffix=".zip", prefix=f"pixdo_ugoira_{lid}_")
        os.close(fd)
        ok = False
        with api_session.get(meta["zip_url"],
                             headers={"Referer": d.get("url") or "https://www.pixiv.net/"},
                             stream=True, timeout=60) as r:
            if r.status_code == 200:
                with open(tmp_path, "wb") as f:
                    for chunk in r.iter_content(64 * 1024):
                        if _should_stop():
                            return None
                        f.write(chunk)
                ok = os.path.getsize(tmp_path) > 1000
        if not ok:
            _log("  [动图] 动图包下载失败")
            return None

        delay_map = {os.path.basename(f["file"]): f["delay"] for f in frames_meta}
        fallback_delay = frames_meta[0]["delay"] if frames_meta else 100
        resample = getattr(Image, "LANCZOS", None) or Image.Resampling.LANCZOS

        images, durations = [], []
        with zipfile.ZipFile(tmp_path) as z:
            names = sorted(n for n in z.namelist()
                           if not n.endswith("/") and
                           n.lower().endswith((".jpg", ".jpeg", ".png", ".gif", ".webp")))
            for n in names:
                if _should_stop():
                    return None
                im = Image.open(io.BytesIO(z.read(n))).convert("RGB")
                if max(im.size) > 600:
                    ratio = 600 / max(im.size)
                    im = im.resize((max(1, int(im.width * ratio)),
                                    max(1, int(im.height * ratio))), resample)
                images.append(im)
                durations.append(delay_map.get(os.path.basename(n), fallback_delay))
        if not images:
            _log("  [动图] 包里没有可用帧")
            return None

        likes = int(d.get("like_count") or 0)
        fname = f"{likes:>08d}_{lid}_p0_{sanitize(d['author'])}.gif"
        fpath = os.path.join(folder, fname)
        images[0].save(fpath, save_all=True, append_images=images[1:],
                       duration=durations, loop=0, disposal=2)
        size_kb = os.path.getsize(fpath) // 1024
        _log(f"  [动图] 合成完成：{len(images)} 帧"
             f" {images[0].width}x{images[0].height} · {size_kb} KB")
        return fpath
    except Exception as e:
        _log(f"  [动图] 合成失败: {e}")
        return None
    finally:
        if tmp_path:
            try:
                os.remove(tmp_path)
            except OSError:
                pass


# ============================================================
# 标签联想（输入框自动补全，pixiv 官方联想接口）
# ============================================================

TAG_SUGGEST_URL = "https://www.pixiv.net/rpc/cps.php"

_suggest_session = None
_suggest_lock = threading.Lock()
_tag_cache_lock = threading.Lock()


def _get_suggest_session():
    """联想专用会话：接口游客即可用。
    注意不能带可能过期的登录 cookie（过期会话会导致接口返回 400）。"""
    global _suggest_session
    with _suggest_lock:
        if _suggest_session is None:
            s = requests.Session()
            s.headers.update({"User-Agent": UA,
                              "Referer": "https://www.pixiv.net/",
                              "Accept-Language": "zh-CN,zh;q=0.9,ja;q=0.8,en;q=0.7"})
            _suggest_session = s
        return _suggest_session


def _tag_cache_path():
    return CONFIG.get("tag_cache_file") or os.path.join(_base_dir, "tag_suggest_cache.json")


def _load_tag_cache():
    try:
        with open(_tag_cache_path(), encoding="utf-8") as f:
            data = json.load(f)
        if isinstance(data, dict):
            if not isinstance(data.get("queries"), dict):
                data["queries"] = {}
            if not isinstance(data.get("pool"), dict):
                data["pool"] = {}
            return data
    except Exception:
        pass
    return {"queries": {}, "pool": {}}


def _save_tag_cache(cache):
    """写缓存；顺带控制规模，防止无限增长"""
    try:
        q = cache.get("queries") or {}
        if len(q) > 2000:
            for k in list(q.keys())[:500]:
                q.pop(k, None)
        pool = cache.get("pool") or {}
        if len(pool) > 20000:
            items = sorted(pool.values(),
                           key=lambda x: -int(x.get("access_count") or 0))
            cache["pool"] = {it["tag_name"]: it for it in items[:15000]}
        path = _tag_cache_path()
        tmp = path + ".tmp"
        with open(tmp, "w", encoding="utf-8") as f:
            json.dump(cache, f, ensure_ascii=False)
        os.replace(tmp, path)
    except Exception:
        pass


def _norm_candidate(c):
    try:
        count = int(c.get("access_count") or 0)
    except (TypeError, ValueError):
        count = 0
    return {"tag_name": str(c.get("tag_name") or "").strip(),
            "translation": str(c.get("tag_translation") or "").strip(),
            "access_count": count,
            "type": str(c.get("type") or "")}


def _search_tag_pool(pool, keyword, limit):
    """离线回退：在历史标签池里做子串匹配（名称/翻译）。
    简繁与异体字归一后匹配（如 圣娅→圣亚、园→園），前缀优先、热度次之。"""
    kw = keyword.lower()
    if not kw:
        return []
    kwc = _tag_canon(kw)
    scored = []
    for it in (pool or {}).values():
        name = it.get("tag_name") or ""
        trans = it.get("translation") or ""
        nl, tl = name.lower(), trans.lower()
        nlc = _tag_canon(nl)
        tlc = _tag_canon(tl) if tl else ""
        hit = (kw in nl) or (tl and kw in tl) or \
              (kwc and (kwc in nlc or (tlc and kwc in tlc)))
        if hit:
            prefix = nl.startswith(kw) or (tl and tl.startswith(kw)) or \
                     (kwc and (nlc.startswith(kwc) or (tlc and tlc.startswith(kwc))))
            scored.append((0 if prefix else 1,
                           -int(it.get("access_count") or 0), it))
    scored.sort(key=lambda x: (x[0], x[1]))
    return [it for _, _, it in scored[:limit]]


# ---- 联想匹配辅助：简繁/异体字归一 + 逐级去尾（与安卓端 TagSuggester 同源）----

# 简体 → 繁体/日文汉字（覆盖 ACG 标签常见字）
_TAG_TRAD_PAIRS = (
    "园園亚亞圣聖娅婭樱櫻猫貓爱愛优優龙龍东東学學见見绪緒织織团團结結线線纺紡岛島风風剑劍华華丽麗梦夢觉覺归歸来來乐樂术術书書谁誰语語话話认認让讓说說读讀词詞试試题題页頁贝貝车車马馬鸟鳥鱼魚龟龜齐齊仓倉们們个個为為无無义義实實参參双雙欢歡观觀劝勸对對时時树樹极極构構标標样樣机機权權边邊传傳价價众眾会會体體儿兒关關兴興军軍农農冲衝决決况況减減凤鳳划劃则則刚剛创創动動劳勞势勢区區医醫卫衛发發变變号號叶葉听聽吗嗎员員响響问問单單卖賣图圖场場块塊声聲处處备備复復头頭夺奪妈媽宝寶宫宮宾賓岁歲岗崗岭嶺币幣师師带帶帮幫广廣庆慶库庫应應废廢开開异異弃棄张張弥彌弹彈录錄彻徹径徑态態怀懷恶惡惊驚惯慣战戰户戶扑撲执執扩擴扫掃扬揚护護报報担擔拥擁择擇挂掛换換据據摆擺敌敵数數断斷旧舊显顯晓曉暂暫条條杨楊枪槍检檢楼樓欧歐残殘杀殺杂雜齿齒龄齡凯凱凛凜枫楓绫綾辉輝纱紗恋戀灯燈银銀凉涼莲蓮绘繪纯純绝絕绿綠红紅缘緣绀紺")
_TAG_TRAD = {_TAG_TRAD_PAIRS[i]: _TAG_TRAD_PAIRS[i + 1]
             for i in range(0, len(_TAG_TRAD_PAIRS) - 1, 2)}
# 常见异体写法归一（如 圣娅 / 圣亚 两种粉丝常用译名）
_TAG_VARIANT = {"娅": "亚"}


def _tag_to_trad(s):
    return "".join(_TAG_TRAD.get(c, c) for c in s)


def _tag_canon(s):
    """归一化：异体字统一 + 简繁统一 + 小写（仅用于比较，不用于展示）"""
    s = s.lower()
    return "".join(_TAG_TRAD.get(_TAG_VARIANT.get(c, c), _TAG_VARIANT.get(c, c))
                   for c in s)


def _tag_query_levels(keyword, max_levels=6):
    """逐级去尾的查询变体（每层含 原文 + 繁体变体）：
    百合园圣娅 → [[百合园圣娅, 百合園聖婭], [百合园圣, 百合園聖], [百合园, 百合園], ...]
    """
    out, cur, lv = [], keyword, 0
    while len(cur) >= 2 and lv < max_levels:
        out.append(list(dict.fromkeys([cur, _tag_to_trad(cur)])))
        cur, lv = cur[:-1], lv + 1
    return out


def _tag_common_prefix(a, b):
    i = 0
    while i < len(a) and i < len(b) and a[i] == b[i]:
        i += 1
    return i


def _tag_score(keyword, item):
    """打分：与输入（归一化后）的公共前缀越长越相关；中文翻译命中同等计分"""
    a = _tag_canon(keyword)
    if not a:
        return 0
    best = _tag_common_prefix(a, _tag_canon(item.get("tag_name") or ""))
    trans = item.get("translation") or ""
    if trans:
        best = max(best, _tag_common_prefix(a, _tag_canon(trans)))
    return best


def _fetch_suggest(keyword, timeout):
    """单次在线联想查询（纯游客会话）"""
    try:
        q = urllib.parse.quote(keyword)
        r = _get_suggest_session().get(f"{TAG_SUGGEST_URL}?keyword={q}&lang=zh",
                                       timeout=timeout)
        if r.status_code != 200:
            return []
        cands = r.json().get("candidates")
        if not isinstance(cands, list):
            return []
        seen, out = set(), []
        for c in cands:
            if not isinstance(c, dict):
                continue
            it = _norm_candidate(c)
            if it["tag_name"] and it["tag_name"] not in seen:
                seen.add(it["tag_name"])
                out.append(it)
        return out
    except Exception:
        return []


def suggest_tags(keyword, limit=10, timeout=6):
    """实时标签联想（搜索框下拉候选）。

    pixiv 官方联想接口 rpc/cps.php 只做「前缀匹配」（对 tag 名或中文翻译），实测：
      百合园 → 仅 1 条；百合園（繁体变体）→ 6 条；百合园圣 → 1 条；
      圣娅 / 凯伊 / 未花 这类中间、尾部片段 → 0 条
    因此查询时做「原文 + 简繁变体 + 逐级去尾」，返回后按与输入的公共前缀长度排序；
    查过的结果写入本地池（tag_suggest_cache.json），之后中文片段也能离线命中。

    返回: [{"tag_name": str, "translation": str, "access_count": int, "type": str}, ...]
    """
    keyword = (keyword or "").strip()
    if not keyword:
        return []

    with _tag_cache_lock:
        cache = _load_tag_cache()
        cached = (cache.get("queries") or {}).get(keyword)
    if cached:
        return cached[:limit]

    merged = {}      # tag_name -> item
    for variants in _tag_query_levels(keyword):
        with ThreadPoolExecutor(max_workers=2) as ex:
            results = list(ex.map(lambda v: _fetch_suggest(v, timeout), variants))
        for lst in results:
            for it in lst:
                name = it["tag_name"]
                old = merged.get(name)
                if old is None:
                    merged[name] = it
                    continue
                o_t = old.get("translation") or ""
                n_t = it.get("translation") or ""
                if (not o_t and n_t) or (bool(o_t) == bool(n_t) and
                                         it["access_count"] > old["access_count"]):
                    merged[name] = it
        if len(merged) >= 6:
            break

    if merged:
        ranked = sorted(merged.values(),
                        key=lambda x: (-_tag_score(keyword, x),
                                       -int(x.get("access_count") or 0)))[:limit]
        with _tag_cache_lock:
            cache = _load_tag_cache()
            (cache.setdefault("queries", {}))[keyword] = ranked
            pool = cache.setdefault("pool", {})
            for it in ranked:
                pool[it["tag_name"]] = it
            _save_tag_cache(cache)
        return ranked

    # 在线无结果 / 网络失败 → 用历史标签池做（归一化）子串匹配兜底
    with _tag_cache_lock:
        pool = _load_tag_cache().get("pool")
    return _search_tag_pool(pool, keyword, limit)


# ============================================================
# 下载
# ============================================================

def download_image(url, path, referer, api_session):
    if not url:
        return False
    try:
        resp = api_session.get(url,
                               headers={"Referer": referer,
                                        "Accept": "image/avif,image/webp,image/*,*/*;q=0.8"},
                               timeout=30, stream=True)
        if resp.status_code == 200:
            content = resp.content
            if len(content) > 1000:
                with open(path, "wb") as f:
                    f.write(content)
                return True
        # 静默失败（不刷屏）
        return False
    except Exception:
        return False


# ============================================================
# 查重记录（SQLite 表）
# ============================================================

_HIST_COLS = ("illust_id title author author_id like_count is_r18 page_count "
              "tags url status reason folder files created_at updated_at").split()


def _file_ok(path):
    """文件存在且非空"""
    try:
        return os.path.getsize(path) > 0
    except OSError:
        return False


def _now():
    return time.strftime("%Y-%m-%d %H:%M:%S")


class HistoryStore:
    """跨运行查重表。

    状态:
      downloaded = 全部页面都在(将被跳过, 不再下载)
      missing    = 图片被手动删除/下载不完整(重新出现时补下载缺失的页)
      filtered   = 被过滤条件排除(低赞/AI 等; 默认也跳过, 可把
                   dedup_skip_filtered 设为 False 让它们每次重新检查)

    手动删除图片的同步:
      每次运行开始时 reconcile() 会检查所有记录的文件是否还在,
      被删除的记录自动标记为 missing; 该作品下次出现时会重新下载。
      运行中遇到文件缺失的也会即时改状态。
    """

    _UPSERT = """INSERT INTO works
        (illust_id,title,author,author_id,like_count,is_r18,page_count,
         tags,url,status,reason,folder,files,created_at,updated_at)
        VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)
        ON CONFLICT(illust_id) DO UPDATE SET
            title=excluded.title, author=excluded.author,
            author_id=excluded.author_id, like_count=excluded.like_count,
            is_r18=excluded.is_r18, page_count=excluded.page_count,
            tags=excluded.tags, url=excluded.url, status=excluded.status,
            reason=excluded.reason, folder=excluded.folder,
            files=excluded.files, updated_at=excluded.updated_at"""

    def __init__(self, db_path, skip_filtered=True):
        self.db_path = db_path
        self.skip_filtered = skip_filtered
        self.conn = None
        self.records = {}

    # ---------------- 基础 ----------------
    def open(self):
        self.conn = sqlite3.connect(self.db_path, timeout=10)
        self.conn.execute("""CREATE TABLE IF NOT EXISTS works (
            illust_id  TEXT PRIMARY KEY,
            title      TEXT,
            author     TEXT,
            author_id  TEXT,
            like_count INTEGER,
            is_r18     INTEGER,
            page_count INTEGER,
            tags       TEXT,
            url        TEXT,
            status     TEXT,
            reason     TEXT,
            folder     TEXT,
            files      TEXT,
            created_at TEXT,
            updated_at TEXT)""")
        self.conn.commit()
        self.records = {}
        for row in self.conn.execute(f"SELECT {','.join(_HIST_COLS)} FROM works"):
            rec = dict(zip(_HIST_COLS, row))
            try:
                files = json.loads(rec.get("files") or "[]")
            except Exception:
                files = []
            rec["file_list"] = files if isinstance(files, list) else []
            self.records[str(rec["illust_id"])] = rec

    def close(self):
        if self.conn is not None:
            try:
                self.conn.close()
            finally:
                self.conn = None

    def summary(self):
        n = {"downloaded": 0, "missing": 0, "filtered": 0}
        for r in self.records.values():
            if r.get("status") in n:
                n[r["status"]] += 1
        return (f"共 {len(self.records)} 条（已下载 {n['downloaded']} / "
                f"文件缺失 {n['missing']} / 已过滤 {n['filtered']}）")

    # ---------------- 文件状态 ----------------
    @staticmethod
    def is_complete(rec):
        """记录中的文件是否齐全（数量够页数 且 文件都存在且非空）"""
        files = rec.get("file_list") or []
        if not files or len(files) < int(rec.get("page_count") or 1):
            return False
        return all(_file_ok(p) for p in files)

    def reconcile(self):
        """对账: 表里的文件被手动删除/恢复后同步状态。返回变更条数"""
        changed = 0
        for rec in self.records.values():
            if rec.get("status") not in ("downloaded", "missing"):
                continue
            new = "downloaded" if self.is_complete(rec) else "missing"
            if new != rec["status"]:
                rec["status"] = new
                self._set_status(rec)
                changed += 1
        return changed

    def _set_status(self, rec):
        try:
            self.conn.execute("UPDATE works SET status=?, updated_at=? WHERE illust_id=?",
                              (rec["status"], _now(), rec["illust_id"]))
            self.conn.commit()
        except Exception:
            pass

    # ---------------- 查询 ----------------
    def should_skip(self, illust_id, is_ugoira=False):
        """是否需要跳过。返回 (skip, reason)"""
        rec = self.records.get(str(illust_id))
        if not rec:
            return False, ""
        st = rec.get("status")
        if st == "downloaded":
            files = rec.get("file_list") or []
            # 动图：旧记录里没有 .gif（过去只能下到静态首帧）→ 当作未完成重新下载
            if is_ugoira and not any(str(f).lower().endswith(".gif") for f in files):
                rec["status"] = "missing"
                self._set_status(rec)
                return False, ""
            if self.is_complete(rec):
                return True, "已下载"
            # 文件已被删除 → 更新表, 当作未处理
            rec["status"] = "missing"
            self._set_status(rec)
            return False, ""
        if st == "filtered" and self.skip_filtered:
            return True, "已过滤"
        return False, ""

    def files_of(self, illust_id):
        rec = self.records.get(str(illust_id))
        return list(rec.get("file_list") or []) if rec else []

    # ---------------- 写入 ----------------
    def _upsert(self, rec):
        self.conn.execute(self._UPSERT, (
            rec["illust_id"], rec.get("title", ""), rec.get("author", ""),
            rec.get("author_id", ""), rec.get("like_count", 0),
            1 if rec.get("is_r18") else 0, rec.get("page_count", 1),
            rec.get("tags", "[]"), rec.get("url", ""), rec.get("status", ""),
            rec.get("reason", ""), rec.get("folder", ""), rec.get("files", "[]"),
            rec.get("created_at", _now()), rec.get("updated_at", _now())))
        self.conn.commit()
        self.records[str(rec["illust_id"])] = rec

    def record_downloaded(self, d, folder, files, expected):
        """记录已处理的作品。files: 实际存在的文件列表; expected: 应有页数"""
        lid = str(d["illust_id"])
        present = [f for f in files if _file_ok(f)]
        now = _now()
        old = self.records.get(lid) or {}
        complete = expected > 0 and len(present) >= expected
        rec = {
            "illust_id": lid,
            "title": d.get("title", ""),
            "author": d.get("author", ""),
            "author_id": str(d.get("author_id", "")),
            "like_count": int(d.get("like_count") or 0),
            "is_r18": 1 if d.get("is_r18") else 0,
            "page_count": int(expected or d.get("page_count") or 1),
            "tags": json.dumps(d.get("tags") or [], ensure_ascii=False),
            "url": d.get("url", ""),
            "status": "downloaded" if complete else "missing",
            "reason": "",
            "folder": folder,
            "files": json.dumps(present, ensure_ascii=False),
            "created_at": old.get("created_at") or now,
            "updated_at": now,
        }
        rec["file_list"] = present
        self._upsert(rec)

    def record_filtered(self, d, reason):
        """记录被过滤的作品（低赞/AI/R18模式不符等）"""
        lid = str(d["illust_id"])
        old = self.records.get(lid) or {}
        now = _now()
        rec = {
            "illust_id": lid,
            "title": d.get("title", ""),
            "author": d.get("author", ""),
            "author_id": str(d.get("author_id", "")),
            "like_count": int(d.get("like_count") or 0),
            "is_r18": 1 if d.get("is_r18") else 0,
            "page_count": int(d.get("page_count") or 1),
            "tags": json.dumps(d.get("tags") or [], ensure_ascii=False),
            "url": d.get("url", ""),
            "status": "filtered",
            "reason": reason,
            "folder": old.get("folder", ""),
            "files": old.get("files") or "[]",
            "created_at": old.get("created_at") or now,
            "updated_at": now,
        }
        rec["file_list"] = old.get("file_list") or []
        self._upsert(rec)


def clear_history():
    """清空查重记录（删除数据库文件）。返回 (是否成功, 消息)"""
    path = CONFIG.get("history_db")
    if not path:
        return False, "未配置查重库路径"
    try:
        removed = False
        for suffix in ("", "-wal", "-shm", "-journal"):
            p = path + suffix
            if os.path.exists(p):
                os.remove(p)
                removed = True
        return True, (f"查重记录已清空: {path}" if removed else "查重记录本来就是空的")
    except OSError as e:
        return False, f"清空失败（文件可能被占用）: {e}"


# ============================================================
# 主流程
# ============================================================

# GUI/外部调用钩子
_log_callback = None       # 日志回调: fn(str)
_stop_flag = False         # 停止标志


def _log(msg):
    # 同时输出到控制台和 GUI 回调（windowed exe 中 stdout 为 None，需保护）
    try:
        print(msg)
    except (OSError, AttributeError):
        pass
    if _log_callback:
        try:
            _log_callback(msg)
        except Exception:
            pass


def _should_stop():
    # 检查是否请求停止
    return _stop_flag


def stop_scraper():
    # 请求停止爬虫
    global _stop_flag
    _stop_flag = True


def run_scraper(config_override=None, log_callback=None):
    # 可外部调用的入口，返回 {"ok": True/False, ...}
    global _log_callback, _stop_flag, CONFIG
    _log_callback = log_callback
    _stop_flag = False
    original = dict(CONFIG)
    if config_override:
        CONFIG.update(config_override)
    try:
        return _main_impl()
    finally:
        CONFIG.clear()
        CONFIG.update(original)
        _log_callback = None
        _stop_flag = False


def _main_impl():
    org_tags = CONFIG.get("organize_by_tags")
    org_str = ""
    if isinstance(org_tags, list) and org_tags:
        org_str = " | 标签分类: " + ", ".join(org_tags)
    elif org_tags:
        org_str = " | 标签分类: 自动(首个非AI标签)"

    sep = "=" * 60
    r18_mode = "仅R18" if CONFIG.get("r18_only") else ("不含R18" if not CONFIG.get("include_r18", True) else "含R18")
    _log(f"\n{sep}\n  Pixiv Scraper\n  标签: {CONFIG['tag']}"
         f" | 排序: {CONFIG['order']} | 目标: {CONFIG['max_images']} 张"
         f"\n  最低点赞: {CONFIG['min_likes']} | AI过滤: {CONFIG['filter_ai']}"
         f" | R18分夹: {CONFIG['separate_r18']} | R18模式: {r18_mode}"
         f" | 查重: {'开' if CONFIG.get('dedup') else '关'}{org_str}"
         f"\n{sep}")

    os.makedirs(CONFIG["download_dir"], exist_ok=True)

    # 无 Cookie 文件时强制显示浏览器，以便手动登录
    if not os.path.exists(CONFIG["cookie_file"]):
        CONFIG["show_browser"] = True
        _log("[*] 未找到 Cookie 文件，将打开浏览器进行手动登录")

    # 打开查重库并与磁盘对账（手动删除的图片会在这里被检测到）
    history = None
    if CONFIG.get("dedup", True):
        try:
            history = HistoryStore(CONFIG["history_db"],
                                   skip_filtered=CONFIG.get("dedup_skip_filtered", True))
            history.open()
            _log(f"[*] 查重库: {CONFIG['history_db']} | {history.summary()}")
            changed = history.reconcile()
            if changed:
                _log(f"[*] 查重: {changed} 条记录的文件被删除/恢复，已更新状态")
        except Exception as e:
            _log(f"[!] 查重库打开失败（本次不做去重）: {e}")
            history = None

    driver = None
    try:
        driver = create_driver()
        driver.maximize_window()


        if _should_stop():
            return {"ok": False, "reason": "用户停止"}

        ensure_logged_in(driver)

        if _should_stop():
            return {"ok": False, "reason": "用户停止"}

        api = build_session(driver)
        if _session_logged_in(api) is True:
            _log("[✓] 登录状态: 已登录")
        else:
            _log("[!] 登录状态: 未登录（游客）！R18 作品不会出现在搜索结果中。")
            _log("    解决: 删除 cookies.pkl 后重新运行并完成登录; 并确认 pixiv")
            _log("    「设置 → 閲覧設定 → R-18作品の表示」已开启。")

        if _should_stop():
            return {"ok": False, "reason": "用户停止"}

        _log("\n[*] 搜索作品...")
        if CONFIG.get("r18_only"):
            search_modes = ["r18"]                 # 仅 R18: 直接用 R18 搜索
        elif CONFIG.get("include_r18", True):
            search_modes = ["all", "r18"]          # 含 R18: 补一轮 R18 搜索, 避免漏掉 R18 作品
        else:
            search_modes = ["all"]
        target = CONFIG["max_images"]
        candidates, seen = [], set()
        pages = {m: 1 for m in search_modes}       # 各 mode 下一待翻页码
        mode_done = {m: False for m in search_modes}
        processed = set()                          # 已走过详情筛选的候选 id
        r18_cand = 0
        skipped_dup = 0
        pages_scanned = 0

        min_likes = CONFIG["min_likes"]
        include_r18 = CONFIG["include_r18"]
        r18_only = CONFIG.get("r18_only", False)
        mode_label = ("仅R18" if r18_only else ("不含R18" if not include_r18 else "含R18"))
        _log(f"\n[*] 获取详情 (≥{min_likes}赞, 过滤AI, {mode_label})...")

        details = []
        stats = {"low": 0, "ai": 0, "noimg": 0, "r18": 0, "safe": 0}

        # 关键：筛选出的作品不足目标数量时，继续翻页扩大扫描，直到满足 / 搜索穷尽
        while len(details) < target:
            # ---- 补充候选：保证“未处理候选”至少有 target 个（每个 mode 至少翻过第 1 页）----
            for mode in search_modes:
                while (len(candidates) - len(processed) < target or pages[mode] == 1) \
                        and not mode_done[mode] and pages[mode] <= 50:
                    if _should_stop():
                        return {"ok": False, "reason": "用户停止"}
                    items = search_api(api, CONFIG["tag"], CONFIG["order"],
                                       pages[mode], mode)
                    pages_scanned += 1
                    if not items:
                        _log(f"  [{mode}] 第 {pages[mode]} 页无结果，结束")
                        mode_done[mode] = True
                        break
                    added = dup = 0
                    for it in items:
                        if it["illust_id"] in seen:
                            continue
                        seen.add(it["illust_id"])
                        if it.get("illust_type") == 1:
                            continue                      # 漫画暂不下载
                        if history and history.should_skip(
                                it["illust_id"], it.get("illust_type") == 2)[0]:
                            dup += 1
                            skipped_dup += 1
                            continue
                        candidates.append(it)
                        if it.get("x_restrict"):
                            r18_cand += 1
                        added += 1
                    if added or dup:
                        _log(f"  [{mode}] 第 {pages[mode]} 页: 新增 {added}，查重跳过 {dup}"
                             f" (累计新 {len(candidates)}，共跳过 {skipped_dup})")
                    else:
                        mode_done[mode] = True        # 整页都是见过的条目（翻页未生效）
                        break
                    pages[mode] += 1
                    time.sleep(CONFIG["api_delay"])

            # ---- 详情筛选：处理所有尚未筛选的候选 ----
            for c in candidates:
                if c["illust_id"] in processed:
                    continue
                if _should_stop():
                    return {"ok": False, "reason": "用户停止"}
                processed.add(c["illust_id"])
                d = detail_api(api, c["illust_id"])
                d["title"] = d["title"] or c.get("title", "")
                d["author"] = d["author"] or c.get("user_name", "")
                d["author_id"] = d["author_id"] or c.get("user_id", "")
                likes = d["like_count"]
                imgs = len(d["image_urls"])

                if min_likes and likes < min_likes:
                    stats["low"] += 1
                    lbl = f"x {likes}赞"
                    if history:
                        history.record_filtered(d, "low_likes")
                elif imgs == 0:
                    stats["noimg"] += 1
                    lbl = "x 无图"      # 不写入查重库: 可能是临时失败, 下次重试
                elif CONFIG["filter_ai"] and has_ai_tag(d["tags"]):
                    stats["ai"] += 1
                    lbl = "x AI"
                    if history:
                        history.record_filtered(d, "ai")
                elif not include_r18 and d["is_r18"]:
                    stats["r18"] += 1
                    lbl = "x R18"
                    if history:
                        history.record_filtered(d, "r18_excluded")
                elif r18_only and not d["is_r18"]:
                    stats["safe"] += 1
                    lbl = "x 非R18"
                    if history:
                        history.record_filtered(d, "safe_excluded")
                else:
                    lbl = f"OK likes{likes} {imgs}图"
                    details.append(d)

                _log(f"  [{len(processed)}/{len(candidates)}] {c['illust_id']}: "
                     f"{c['title'][:30]} {lbl}")
                time.sleep(CONFIG["api_delay"])

                if stats["low"] >= 20 and len(details) >= target:
                    _log("  [*] 足够候选，停止详情获取")
                    break
                if len(details) >= target * 3:
                    _log("  [*] 候选充足，停止详情获取")
                    break

            if len(details) >= target:
                break
            if all(mode_done[m] or pages[m] > 50 for m in search_modes):
                _log(f"[*] 搜索结果已穷尽（共扫描 {pages_scanned} 页）")
                break

        if skipped_dup:
            _log(f"[*] 查重: 跳过 {skipped_dup} 个已处理过的作品")
        _log(f"\n[*] 共收集 {len(candidates)} 个作品（其中标记 R18 的 {r18_cand} 个）"
             f"，已扫描 {pages_scanned} 页")
        if not candidates:
            if skipped_dup:
                _log("[*] 没有新作品：搜索范围内的作品都已处理过（查重跳过）")
                return {"ok": True, "downloaded": 0, "total_collected": 0,
                        "skipped_dup": skipped_dup}
            _log("[!] 无结果，请检查标签名或登录状态")
            return {"ok": False, "reason": "无搜索结果"}
        if CONFIG.get("include_r18", True) and r18_cand == 0:
            _log("[!] 搜索结果里没有 R18 作品：可能是未登录（游客）、Cookie 失效，")
            _log("    或账号未开启「R-18作品の表示」（设置 → 閲覧設定）。")

        _log(f"\n[*] 低赞:{stats['low']} AI:{stats['ai']} 无图:{stats['noimg']}"
             f" R18跳过:{stats['r18']} 非R18跳过:{stats['safe']} -> 有效:{len(details)}")
        if len(details) < target:
            _log(f"[!] 满足条件的作品只有 {len(details)} 个（目标 {target}）："
                 f"已尽力扩大扫描，可尝试降低最低点赞或关闭 AI 过滤")

        if _should_stop():
            return {"ok": False, "reason": "用户停止"}

        if not details:
            _log("[*] 没有符合条件的作品可下载")
            return {"ok": True, "downloaded": 0, "skipped_dup": skipped_dup}

        details.sort(key=lambda x: x["like_count"], reverse=True)
        if details:
            ls = [d["like_count"] for d in details]
            _log(f"[*] 点赞范围: {min(ls)} ~ {max(ls)}, 平均: {sum(ls)//len(ls)}")

        _log(f"\n[*] 开始下载...")
        dl = 0
        meta = []
        base = os.path.join(CONFIG["download_dir"], sanitize(CONFIG["tag"]))

        for d in details:
            if _should_stop():
                _log("\n[*] 用户停止下载")
                break
            if dl >= CONFIG["max_images"]:
                break

            is_r18 = d["is_r18"]
            if is_r18 and not CONFIG["include_r18"]:
                continue
            if not is_r18 and CONFIG.get("r18_only", False):
                continue

            folder = os.path.join(base, "r18" if is_r18 else "safe")
            os.makedirs(folder, exist_ok=True)

            lid = d["illust_id"]
            likes = d["like_count"]
            author = d["author"]
            title = d["title"]
            urls = d["image_urls"]
            ref = d["url"]

            # 旧文件索引：点赞数变化会导致文件名变化，按页号沿用旧文件
            old_by_page = {}
            if history:
                for old_f in history.files_of(lid):
                    m = re.search(rf"_{re.escape(lid)}_p(\d+)_", os.path.basename(old_f))
                    if m:
                        old_by_page[int(m.group(1))] = old_f

            ok_cnt = 0
            saved = []
            is_ugoira = d.get("illust_type") == 2
            total_pages = 1 if is_ugoira else len(urls)

            if is_ugoira:
                # 动图：下载帧序列 zip → 合成为可播放的 GIF
                gif_path = download_ugoira(d, folder, api)
                if gif_path:
                    ok_cnt = 1
                    saved.append(gif_path)
            else:
                for j, img_url in enumerate(urls):
                    if _should_stop():
                        break
                    ext = os.path.splitext(img_url.split("?")[0])[1] or ".jpg"
                    if ext not in (".jpg", ".jpeg", ".png", ".gif", ".webp"):
                        ext = ".jpg"
                    fname = f"{likes:>08d}_{lid}_p{j}_{sanitize(author)}{ext}"
                    fpath = os.path.join(folder, fname)
                    if _file_ok(fpath):                      # 已存在 → 跳过下载
                        ok_cnt += 1
                        saved.append(fpath)
                        continue
                    of = old_by_page.get(j)                  # 沿用旧文件名（若还在）
                    if of and _file_ok(of):
                        ok_cnt += 1
                        saved.append(of)
                        continue
                    if download_image(img_url, fpath, ref, api):
                        ok_cnt += 1
                        saved.append(fpath)
                    time.sleep(CONFIG["download_delay"])

            if history and ok_cnt:
                history.record_downloaded(d, folder, saved, total_pages)

            if ok_cnt:
                dl += 1
                meta.append({"illust_id": lid, "title": title, "author": author,
                             "author_id": d["author_id"], "like_count": likes,
                             "view_count": d.get("view_count", 0),
                             "bookmark_count": d.get("bookmark_count", 0),
                             "is_r18": is_r18, "tags": d["tags"], "url": ref,
                             "ok": ok_cnt, "total": total_pages})
                r18s = " [R18]" if is_r18 else " [safe]"
                kind = " [动图]" if is_ugoira else ""
                _log(f"  [{dl}/{CONFIG['max_images']}]{r18s}{kind} likes {likes:>6} "
                     f"{title[:40]} | {ok_cnt}/{total_pages}")

            if dl >= CONFIG["max_images"]:
                break

        mp = os.path.join(base, "metadata.json")
        with open(mp, "w", encoding="utf-8") as f:
            json.dump(meta, f, ensure_ascii=False, indent=2)

        _log(f"\n{sep}\n  完成！下载 {dl} 个作品\n  目录: {os.path.abspath(base)}\n{sep}")
        if meta:
            _log("\n  Top 10:")
            for r, m in enumerate(meta[:10], 1):
                _log(f"  {r:2d}. likes {m['like_count']:>8,}  {m['title'][:45]}  by {m['author']}")

        return {"ok": True, "downloaded": dl, "total_collected": len(details),
                "skipped_dup": skipped_dup}

    except Exception as e:
        tb = traceback.format_exc()
        _log(f"\n[!] 错误: {e}\n{tb}")
        return {"ok": False, "reason": str(e), "traceback": tb}
    finally:
        if history is not None:
            try:
                history.close()
            except Exception:
                pass
        if driver is not None:
            try:
                driver.quit()
            except Exception:
                pass


if __name__ == "__main__":
    _main_impl()
